version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
    networks:
      - app-network
    depends_on:
      - postgres

  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - backend/.env
  #   networks:
  #     - app-network
  #   depends_on:
  #     - postgres

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    networks:
      - app-network

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    networks:
      - app-network
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
