name: championship-platform-image
services:
  fastapi:
    public: true
    image: marciogpc/championship-platform-image:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi
