name: Backend Build

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || contains(github.event.pull_request.changed_files, 'backend/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          pytest

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./backend/Dockerfile
          push: true
          tags: ${{ github.sha }}
